<?xml version="1.0"?>
<!-- XSLT stylesheet that generates localized versions of the page header. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:template match="header-menu">
    <xsl:comment>This file is automatically generated.  Do not edit!</xsl:comment>

    <div id="header-box">
      <div id="header" class="box">
        <div id="title">
      	  <h1><a href="./">
	      <img src="http://mirrors.creativecommons.org/dev/oesearch/images/oes-logo.png" border="0" />
	  </a></h1>
      	</div>
      </div>
    </div>

  </xsl:template>
</xsl:stylesheet>
